name: 🐞 Bug Report
description: Report a reproducible bug
title: "[Bug]: "
labels: ["bug"]
assignees: []

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Clearly describe the issue.
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Go to ...
        2. Click ...
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      placeholder: |
        - OS:
        - Browser / Node version:
        - App version:
